name: theblue_crown
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  json_annotation: ^4.3.0
  http: ^0.13.4
  sqflite: ^2.0.2
  path: ^1.8.0
  shared_preferences: ^2.0.12
  flutter_svg: ^0.22.0
  status_change: ^2.0.0
  timelines: ^0.1.0
  flutter_staggered_grid_view: ^0.6.0
  flutter_native_splash: ^1.3.3
  dots_indicator: ^2.0.0
  intl: ^0.17.0
  blurrycontainer: ^0.1.0
  badges: ^2.0.2
  lottie: ^1.2.2
  google_maps_flutter: ^2.1.2
  geocoding: ^2.0.4
  geolocator: ^8.2.0
  cached_network_image: ^3.2.0
  flutter_typeahead: ^3.1.3
  flutter_google_places: ^0.3.0
  google_maps_flutter_web: ^0.3.0+2
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  url_strategy:
  image_picker: ^0.8.5
  shimmer: ^2.0.0
  webview_flutter: ^3.0.4
  get_storage: ^2.0.3
  url_launcher: ^6.1.7
  syncfusion_flutter_pdfviewer: ^20.3.59
#  flutter_facebook_auth:


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.0.0


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/language/
    - assets/products/
    - assets/images/splash.png
#    - assets/language/US.json
  #  - assets/fonts/



  #fonts:
  #  - family: SourceSans
  #    fonts:
  #     - asset: assets/fonts/SourceSansPro.ttf